// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhIF24h-7qOBTfTWs1tb_WeHVQndsL-c4',
    appId: '1:932099767351:web:efd1d7b1d1b5864a0613b2',
    messagingSenderId: '932099767351',
    projectId: 'ecommerceapp-ba95d',
    authDomain: 'ecommerceapp-ba95d.firebaseapp.com',
    storageBucket: 'ecommerceapp-ba95d.firebasestorage.app',
    databaseURL: 'https://ecommerceapp-ba95d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVcY5dS5bCiNb4xwqpnnUbb3R7fmjSHrI',
    appId: '1:932099767351:android:d8851fddd7c726530613b2',
    messagingSenderId: '932099767351',
    projectId: 'ecommerceapp-ba95d',
    storageBucket: 'ecommerceapp-ba95d.firebasestorage.app',
    databaseURL: 'https://ecommerceapp-ba95d-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9IrZCuIGt1WOGbZ97Vb0EEp_QItmDAkA',
    appId: '1:932099767351:ios:9e850af13f9b1be00613b2',
    messagingSenderId: '932099767351',
    projectId: 'ecommerceapp-ba95d',
    storageBucket: 'ecommerceapp-ba95d.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreMobileApplicationProject01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9IrZCuIGt1WOGbZ97Vb0EEp_QItmDAkA',
    appId: '1:932099767351:ios:9e850af13f9b1be00613b2',
    messagingSenderId: '932099767351',
    projectId: 'ecommerceapp-ba95d',
    storageBucket: 'ecommerceapp-ba95d.firebasestorage.app',
    iosBundleId: 'com.example.fashionStoreMobileApplicationProject01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhIF24h-7qOBTfTWs1tb_WeHVQndsL-c4',
    appId: '1:932099767351:web:9b69023405994c1b0613b2',
    messagingSenderId: '932099767351',
    projectId: 'ecommerceapp-ba95d',
    authDomain: 'ecommerceapp-ba95d.firebaseapp.com',
    storageBucket: 'ecommerceapp-ba95d.firebasestorage.app',
    databaseURL: 'https://ecommerceapp-ba95d-default-rtdb.firebaseio.com',
  );
}